openapi: 3.0.0
info:
    title: 'Hello World'
    version: 1.0.0
paths:
    /customers: {post: {description: 'Create a new customer', requestBody: {description: 'Customer data', content: {application/json: {schema: {$ref: '#/components/schemas/CreateCustomerDTO'}}}}, responses: {'201': {description: Created, content: {application/json: {example: {id: '1', created_at: '2021-09-01T00:00:00.000Z'}}}}, '400': {description: 'Bad Request', content: {application/json: {example: {error: 'Customer already exists'}}}}}, security: [{apiKeyAuth: []}]}, get: {description: 'Get all customers', responses: {'200': {description: Success, content: {application/json: {example: [{id: '1', name: 'John Doe', email: "", address: ""}]}}}}}}
components:
    schemas: {CreateCustomerDTO: {type: object, required: [name, email, address], properties: {id: {type: string}, name: {type: string}, email: {type: string}, address: {type: string}}}, CustomerDTO: {type: object, properties: {id: {type: string}, name: {type: string}, email: {type: string}, address: {type: string}}}}
tags: []
