name: release

on:
  workflow_run:
    workflows: ['build']
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run release:prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
